device_path_broken: "/sys/bus/w1/devices/28-000008a9cabd"
device_path: "/sys/bus/w1/devices/28-000008a93f40"
high_temp_critical: 29.0
high_temp_warning: 28.0
high_temp: 27.0
low_temp: 25.0
low_temp_warning: 24.0 
low_temp_critical: 23.0
