device_path: "/sys/bus/w1/devices/28-000008a9cabd"
high_temp_critical: "28.0"
high_temp_warning: "27.0"
high_temp: "26.4"
low_temp: "26.1"
low_temp_warning: "25.5" 
low_temp_critical: "24.5"
AMQP_URI: 'pyamqp://guest:guest@localhost'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
rpc_exchange: 'nameko-rpc'
max_workers: 10
parent_calls_tracked: 10
